
### Añadir Json a base
POST http://localhost:3000/
Content-Type: application/json

{
    "nombre": "AAAAAAAAAA",
    "correo": "hola.adios@xd.com",
    "pass": "10000",
    "phone": "1234567"
}

###
PUT http://localhost:3000/
Content-Type: application/json

{
    "id": "6540341315bc5d962df66724",
    "nombre": "AAAAAAAAAA",
    "correo": "hola.adios@xd.com",
    "edad": 10000
}


###
DELETE http://localhost:3000/
Content-Type: application/json

{
    "id": "6548ed9eaf034b5ed8b3a022"
}
